server.port=${API_PORT:8080}
ethereum.node1.url=${ETHEREUM_NODE1_URL:http://localhost:8545}
ethereum.node2.url=${ETHEREUM_NODE2_URL:http://localhost:8547}
ethereum.node3.url=${ETHEREUM_NODE3_URL:http://localhost:8549}
ethereum.node4.url=${ETHEREUM_NODE4_URL:http://localhost:8551}
ethereum.node5.url=${ETHEREUM_NODE5_URL:http://localhost:8553}
